apiVersion: v1
kind: Service
metadata:
  name: dummy-app-ext-service
spec:
  selector:
    app: dummy-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8080
      nodePort: 30163
